### ISSUE TITLE
Error pcap server directory

### ISSUE THREAD

**Issue by chmartin-git** [chmartin-git/No.Z#1]
When trying to install dependancies (npm i) in the server diirectory, an error is issued :
![Sélection_006](https://user-images.githubusercontent.com/43953101/75714713-84d72f00-5ccc-11ea-8873-cf20bd6f0799.png)

**Comment by chmartin-git** [comment]
Read the new step in the README.md file

**Comment by tenzagiri** [comment]
solved by installing :  apt-get install build-essential make
